# Generated by Django 3.2.5 on 2022-08-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='name',
            new_name='name1',
        ),
    ]
