# Generated by Django 3.2.5 on 2022-08-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_name_webpage_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='name1',
            new_name='name',
        ),
    ]
