# Generated by Django 3.2.5 on 2022-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_name1_webpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
